#include <sdktools>
#include <sourcemod>

char g_skins[][] = {
"models/player/gkuo88/kashima/kashima_fix.mdl",
"models/player/gkuo88/prinz/prinzeugen.mdl",
"models/player/hhp227/tenten_loveff/serah.mdl",
"models/player/hibiki/ct_sas.mdl",
"models/player/horseman/horseman.mdl",
"models/player/jacksparrow/jacksparrow.mdl",
"models/player/jgmake/succubus/succubus.mdl",
"models/player/jieshu/azusa/azusa.mdl",
"models/player/jsly/cirno/foxmiko/foxmiko.mdl",
"models/player/jsly/despair/hymiku_fix.mdl",
"models/player/jsly/maliailu_fix.mdl",
"models/player/jsly/suigintou_fix.mdl",
"models/player/jsly/uuz/alice_margatroid.mdl",
"models/player/jsly/uuz/cirno_v2.mdl",
"models/player/jsly/uuz/ene_fix.mdl",
"models/player/jsly/uuz/hasegawa_kobato.mdl",
"models/player/jsly/uuz/hinanawi_tenshi.mdl",
"models/player/jsly/uuz/houjuu_nue.mdl",
"models/player/jsly/uuz/izayoi_sakuya.mdl",
"models/player/jsly/uuz/mystia_lorelei.mdl",
"models/player/jsly/uuz/noire.mdl",
"models/player/jsly/uuz/noumi_kudryavka_fix.mdl",
"models/player/jsly/uuz/nyaruko.mdl",
"models/player/jsly/uuz/plutia.mdl",
"models/player/jsly/uuz/ram.mdl",
"models/player/jsly/uuz/reimu.mdl",
"models/player/jsly/uuz/rom_v2.mdl",
"models/player/jsly/uuz/sanae.mdl",
"models/player/jsly/uuz/satori.mdl",
"models/player/jsly/uuz/terminus_est_fix.mdl",
"models/player/jsly/uuz/usami_renko.mdl",
"models/player/jsly/uuz/youmu_fix.mdl",
"models/player/kirby/regular/umbrella_leet.mdl",
"models/player/kloa500/haruhi/haruhi.mdl",
"models/player/knifelemon/chicleet_black.mdl",
"models/player/knifelemon/cloud.mdl",
"models/player/knifelemon/ranranru.mdl",
"models/player/knifelemon/sea_miku.mdl",
"models/player/knifelemon/slenderman.mdl",
"models/player/knifelemon/spring_miku.mdl",
"models/player/knifelemon/white_chickenleetle/chicleet.mdl",
"models/player/kuristaja/glados_potato/glados_potato.mdl",
"models/player/kuristaja/pbear/pbear.mdl",
"models/player/laalaa_css/laalaa_css.mdl",
"models/player/lockcha/lockcha10/yuki_kotonomiya.mdl",
"models/player/lockcha/lockcha11/glados.mdl",
"models/player/lockcha/lockcha12/kasane_teto.mdl",
"models/player/maxpayne/maxpayne.mdl",
"models/player/pil/agent_smith/smith.mdl",
"models/player/pil/yuna_ffx2/yuna.mdl",
"models/player/pinkbear/pinkbear.mdl",
"models/player/po_css/po_css.mdl",
"models/player/raijin/crocogena/cg.mdl",
"models/player/reisenudongeininaba/reisenudongeininaba_fix.mdl",
"models/player/sam/sam.mdl",
"models/player/sic/hitman/hm_47.mdl",
"models/player/slow/gaycat_v2/gaycat_v2.mdl",
"models/player/techknow/easter/e-bunny.mdl",
"models/player/techknow/gundam/gundam.mdl",
"models/player/techknow/lucario/lucario.mdl",
"models/player/techknow/miku/miku.mdl",
"models/player/techknow/puss/puss.mdl",
"models/player/techknow/p_panther/panther.mdl",
"models/player/techknow/scream/scream.mdl",
"models/player/tinkywinky_css/tinkywinky_css.mdl",
"models/player/ultraman/ultraman.mdl",
"models/player/vad36raccoon_city/vector.mdl",
"models/player/vad36suit/pab/nanosuit.mdl",
"models/player/yoshino/yoshino_fix.mdl",
"models/player/zombieden/artemis/artemis.mdl",
"models/player/zombieden/chino/chino.mdl",
"models/player/zombieden/collection/kongou.mdl",
"models/player/zombieden/collection/northern.mdl",
"models/player/zombieden/collection/yudachi.mdl",
"models/player/zombieden/datealive/kotori_effret.mdl",
"models/player/zombieden/fairy_fencer_f/tiara.mdl",
"models/player/zombieden/fumika/fumika.mdl",
"models/player/zombieden/futaba_anzu/futaba_anzu_headfix.mdl",
"models/player/zombieden/homura/homura.mdl",
"models/player/zombieden/icemega5/kirima_syaro/kirima_syaro.mdl",
"models/player/zombieden/kantaicollection/akatsuki_fix.mdl",
"models/player/zombieden/kantaicollection/hibiki_fix.mdl",
"models/player/zombieden/kantaicollection/ikazuchi.mdl",
"models/player/zombieden/kantaicollection/inazuma.mdl",
"models/player/zombieden/kantaicollection/shigure/shigure.mdl",
"models/player/zombieden/kantaicollection/uduki/uduki_fix.mdl",
"models/player/zombieden/kantaicollection/yamakaze/yamakaze.mdl",
"models/player/zombieden/kantaicollection/yuudachi/yuudachi.mdl",
"models/player/zombieden/lovelive/kousaka_honoka.mdl",
"models/player/zombieden/lovelive/minami_kotori.mdl",
"models/player/zombieden/lovelive/yazawa_niko.mdl",
"models/player/zombieden/miku/cutemiku_fix4.mdl",
"models/player/zombieden/miku/gothic_miku_fix.mdl",
"models/player/zombieden/miku/hoodmiku.mdl",
"models/player/zombieden/miku/kitty_miku_fix.mdl",
"models/player/zombieden/miku/orange_miku.mdl",
"models/player/zombieden/nekopara/azuki.mdl",
"models/player/zombieden/nekopara/coco.mdl",
"models/player/zombieden/neptune/iffy.mdl",
"models/player/zombieden/neptune/nepgearcosplay.mdl",
"models/player/zombieden/neptune/nepgear_8tex.mdl",
"models/player/zombieden/neptune/neptune_wear.mdl",
"models/player/zombieden/neptune/noireswimsuit.mdl",
"models/player/zombieden/neptune/ramcos.mdl",
"models/player/zombieden/neptune/romcos.mdl",
"models/player/zombieden/neptune/uni.mdl",
"models/player/zombieden/neptune/unicos_fix.mdl",
"models/player/zombieden/neptune/unimaid.mdl",
"models/player/zombieden/plclan/tokisaki_mio.mdl",
"models/player/zombieden/rolo/rolo.mdl",
"models/player/zombieden/saber/saber.mdl",
"models/player/zombieden/shana/shana.mdl",
"models/player/zombieden/sophie/sophie.mdl",
"models/player/zombieden/tda/lizzyvolti_miku.mdl",
"models/player/zombieden/touhou/a_cirno/a_cirno_fix.mdl",
"models/player/zombieden/touhou/flandre_scarlet/flandre_scarlet.mdl",
"models/player/zombieden/touhou/marisa/marisa.mdl",
"models/player/zombieden/touhou/momiji/momiji.mdl",
"models/player/zombieden/touhou/mononobe_no_futo/mononobe_no_futo.mdl",
"models/player/zombieden/touhou/remilia_scarlet/remilia_scarlet.mdl",
}


public void OnPluginStart()
{
    HookEvent("player_spawn", Event_PlayerSpawn);
}

public Action Event_PlayerSpawn(Event event,const char[] name,bool dontBroadcast)
{
    int client = GetClientOfUserId(GetEventInt(event, "userid"));
    CreateTimer(0.0, Timer_SetSkin, client);
    return Plugin_Continue;
}

public Action Timer_SetSkin(Handle timer, int client)
{
    if(IsFakeClient(client))
        SetEntityModel(client, g_skins[GetRandomInt(5, 80)]);
    return Plugin_Stop;
}